const films = [
  // --- TITRES EXISTANTS ---
  {
    titre: "TENET",
    duree: "2h15",
    restriction: '+12',
    genre: "Science Fiction-action-thriller-espionnage",
    resolutionmax: "4K",
    synopsis: `Muni d'un seul mot – Tenet – et décidé à se battre pour sauver le monde, notre protagoniste sillonne l'univers crépusculaire de l'espionnage international. Sa mission le projettera dans une dimension qui dépasse le temps. Pourtant, il ne s'agit pas d'un voyage dans le temps, mais d'un renversement temporel…`,
    type: 'Film',
    annee: "2020",
    realisation: "Christopher Nolan",
    distribution: "John David Washington, Robert Pattinson, Elizabeth Debicki",
    favori: false,
    download: false,
    watchtime: 60,
    view: 100000,
    miniPortrait: "TenetPortrait.jpg",      
    titleIMG: "TenetTitle.png",
    miniPaysage: "TenetPaysage.png"
  },
  {
    titre: "Sinners",
    duree: "2h15",
    restriction: '+12',
    genre: "Science Fiction-action-thriller-espionnage",
    resolutionmax: "4K",
    synopsis: `Alors qu’ils cherchent à s’affranchir d’un lourd passé, deux frères jumeaux reviennent dans leur ville natale pour repartir à zéro. Mais ils comprennent qu’une puissance maléfique bien plus redoutable guette leur retour avec impatience…\n\n« À force de danser avec le diable, un beau jour, il viendra te chercher chez toi. »`,
    type: 'Film',
    annee: "2020",
    realisation: "Ryan Coogler",
    distribution: "Michael B. Jordan, Delroy Lindo, Jack O'Connell",
    favori: false,
    download: false,
    watchtime: 0,
    view: 70000,
    miniPortrait: "SinnersPortrait.jpg",
    titleIMG: "SinnersTitle.png",
    miniPaysage: "SinnersPaysage.png"
  },
  {
    titre: "Avengers : Infinity war",
    duree: "2h29",
    restriction: '+12',
    genre: "Science Fiction, Action, Super-héros",
    resolutionmax: "4K",
    synopsis: `Les Avengers et leurs alliés devront être prêts à tout sacrifier pour neutraliser le redoutable Thanos avant que son attaque éclair ne conduise à la destruction complète de l’univers.`,
    type: 'Film',
    annee: "2018",
    realisation: "Anthony et Joe Russo",
    distribution: "Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans, Scarlett Johansson",
    favori: false,
    download: false,
    watchtime: 90,
    view: 800000,
    miniPortrait: "AvergersinfinitywarPortrait.png",
    titleIMG: "AvergersinfinitywarTitle.png",
    miniPaysage: "AvergersinfinitywarPaysage.png"
  },
  {
    titre: "Shrek",
    duree: "1h30",
    restriction: '+7',
    genre: "Animation, Comédie, Famille",
    resolutionmax: "4K",
    synopsis: `Un ogre verdâtre et malodorant vit paisiblement dans son marécage jusqu'au jour où une ribambelle de personnages de contes de fées envahit son territoire. Pour retrouver sa tranquillité, Shrek passe un marché avec Lord Farquaad.`,
    type: 'Film',
    annee: "2001",
    realisation: "Andrew Adamson, Vicky Jenson",
    distribution: "Alain Chabat, Med Hondo, Vincent Cassel",
    favori: false,
    download: false,
    watchtime: 73,
    view: 500000,
    miniPortrait: "ShrekPortrait.jpg",      
    titleIMG: "ShrekTitle.png",
    miniPaysage: "ShrekPaysage.jpg"
  },
  {
    titre: "Astérix mission Cléopatre",
    duree: "1h47",
    restriction: '+7',
    genre: "Comédie, Aventure, Famille",
    resolutionmax: "HD",
    synopsis: `À la demande de Cléopâtre et avec l'aide des Gaulois, Numérobis se lance dans le pari fou d'ériger un palais en 3 mois, tout en déjouant les fourberies d'Amonbofis.`,
    type: 'Film',
    annee: "2002",
    realisation: "Alain Chabat",
    distribution: "Gérard Depardieu, Jamel Debbouze, Christian Clavier, Alain Chabat",
    favori: true,
    download: true,
    watchtime: 100,
    view: 400000,
    miniPortrait: "AsterixmissioncleopatrePortrait.jpg",      
    titleIMG: "AsterixmissioncleopatreTitle.png",
    miniPaysage: "AsterixmissioncleopatrePaysage.png"
  },
  {
    titre: "Case Depart",
    duree: "1h34",
    restriction: '+12',
    genre: "Comédie, Français",
    resolutionmax: "HD",
    synopsis: `Victimes d'un sort, deux demi-frères qui n'ont rien en commun se retrouvent propulsés dans le passé en pleine période esclavagiste aux Antilles. Pour revenir à leur époque, ils vont devoir s'entraider.`,
    type: 'Film',
    annee: "2011",
    realisation: "Fabrice Éboué, Thomas Ngijol, Lionel Steketee",
    distribution: "Fabrice Éboué, Thomas Ngijol, Stéfi Celma, Eriq Ebouaney",
    favori: true,
    download: true,
    watchtime: 0,
    view: 500000,
    miniPortrait: "CasedepartPortrait.jpg",      
    titleIMG: "CasedepartTitle.png",
    miniPaysage: "CasedepartPaysage.jpg"
  },
  {
    titre: "Babylon",
    duree: "3h09",
    restriction: '+16',
    genre: "Drame, Comédie",
    resolutionmax: "4K",
    synopsis: `Hollywood, années 1920 : l'industrie cinématographique amorce sa transition historique du muet au parlant. Le film suit l'ascension fulgurante et la déchéance tragique de personnalités flamboyantes au cœur d'une cité d'excès et de décadence.`,
    type: 'Film',
    annee: "2022",
    realisation: "Damien Chazelle",
    distribution: "Margot Robbie, Brad Pitt, Diego Calva, Tobey Maguire",
    favori: true,
    download: true,
    watchtime: 100,
    view: 600000,
    miniPortrait: "BabylonPortrait.png",      
    titleIMG: "BabylonTitle.png",
    miniPaysage: "BabylonPaysage.png"
  },
  {
    titre: "southpark",
    restriction: '+12',
    genre: "Animation, Comédie, Satire",
    resolutionmax: "HD",
    synopsis: `La petite ville de South Park dans le Colorado est le théâtre des aventures loufoques et irrévérencieuses de Cartman, Stan, Kyle et Kenny, quatre enfants confrontés à l'absurdité du monde des adultes.`,
    type: 'Serie',
    annee: "1997-2024",
    realisation: "Trey Parker, Matt Stone",
    distribution: "Trey Parker, Matt Stone, Mona Marshall",
    favori: false,
    download: false,
    watchtime: 0,
    view: 300000,
    saison: [
      {
        saison: 1,
        episodes: [
          { titre: "Cartman a une sonde anale", duree: "22min", minia: "ep1S1southpark.png", synopsis: "Les aliens implantent un émetteur dans Cartman et kidnappent le frère de Kyle.", watchtime: 98 },
          { titre: "Muscle Plus 4000", duree: "22min", minia: "ep2S1southpark.png", synopsis: "Cartman tente de se muscler en prenant du Muscle Plus 4000. De son côté, M. Garrison essaye d'assassiner Kathie Lee Gifford.", watchtime: 98 },
          { titre: "Volcano", duree: "22min", minia: "ep3S1southpark.png", synopsis: "Les enfants partent à la chasse avec Jimbo, l'oncle de Stan, lorsqu'un volcan entre en éruption.", watchtime: 98 },
          { titre: "Une promenade complètement folle avec Al Super Gay", duree: "22min", minia: "ep4S1southpark.png", synopsis: "Stan découvre que son chien Sparky est gay. Il rencontre Al Super Gay dans son sanctuaire.", watchtime: 98 },
          { titre: "Un éléphant fait l'amour à un cochon", duree: "22min", minia: "ep5S1southpark.png", synopsis: "Les enfants cherchent à faire un croisement génétique entre un éléphant et un cochon de lait.", watchtime: 0 },
          { titre: "La Mort", duree: "22min", minia: "ep6S1southpark.png", synopsis: "Marvin Marsh, le grand-père centenaire de Stan, veut mourir et demande à son petit-fils de l'aider.", watchtime: 98 },
          { titre: "Conjonctivite", duree: "22min", minia: "ep7S1southpark.png", synopsis: "La station spatiale Mir s'écrase sur Kenny et déclenche une épidémie de zombies le soir d'Halloween.", watchtime: 50 },
          { titre: "Le Petit Éthernopien", duree: "22min", minia: "ep8S1southpark.png", synopsis: "Pensant recevoir une montre à quartz, les enfants adoptent par erreur un orphelin éthiopien.", watchtime: 0 },
          { titre: "Monsieur Hankey, le petit caca Noël", duree: "22min", minia: "ep9S1southpark.png", synopsis: "Kyle se sent exclu des festivités de Noël jusqu'à l'arrivée de M. Hankey, le petit caca Noël.", watchtime: 0 },
          { titre: "Damien", duree: "22min", minia: "ep10S1southpark.png", synopsis: "Damien, le fils de Satan, arrive à South Park où son père s'apprête à défier Jésus sur un ring de boxe.", watchtime: 0 },
          { titre: "La mère de Cartman est une folle du cul", duree: "22min", minia: "ep11S1southpark.png", synopsis: "Cartman tente désespérément de découvrir l'identité de son père biologique.", watchtime: 0 }
        ]
      },
      {
        saison: 2,
        episodes: [
          { titre: "Le charmeur de poules", duree: "22min", minia: "ep1S2southpark.png", synopsis: "L'officier Barbrady doit apprendre à lire pour résoudre une série d'agressions insolites contre des poules.", watchtime: 0 },
          { titre: "Les Gnomes voleurs de slips", duree: "22min", minia: "ep2S2southpark.png", synopsis: "Tweek affirme que des gnomes invisibles s'infiltrent chez lui la nuit pour lui dérober ses caleçons.", watchtime: 0 }
        ]
      }
    ],
    miniPortrait: "SouthparkPortrait.jpg",      
    titleIMG: "SouthparkTitle.png",
    miniPaysage: "SouthparkPaysage.jpg"
  },

  // --- VIKINGS (Ajouté avec épisodes locaux complets) ---
  {
    titre: "Vikings",
    type: "Serie",
    annee: "2013-2020",
    restriction: "+16",
    resolutionmax: "4K",
    genre: "Action, Aventure, Drame, Histoire",
    realisation: "Michael Hirst",
    distribution: "Travis Fimmel, Katheryn Winnick, Clive Standen, Gustaf Skarsgård",
    synopsis: `Ragnar Lothbrok, un jeune guerrier viking avide d'aventures et de découvertes, est lassé des pillages traditionnels vers l'Est et rêve d'explorer l'Ouest en traversant l'océan sur des navires innovants conçus par son ami Floki.`,
    favori: true,
    download: true,
    watchtime: 45,
    view: 950000,
    miniPortrait: "VikingsPortrait.jpg",
    miniPaysage: "VikingsPaysage.jpg",
    titleIMG: "VikingsTitle.png",
    saison: [
      {
        saison: 1,
        episodes: [
          { titre: "Cap à l'ouest", duree: "45min", minia: "ep1S1Viking.png", synopsis: "Ragnar Lothbrok est convaincu que des terres riches et inexplorées se trouvent à l'ouest, par-delà la mer Baltique.", watchtime: 98 },
          { titre: "L'expédition", duree: "45min", minia: "ep2S1Viking.png", synopsis: "Ragnar rassemble un équipage d'hommes fidèles pour entreprendre un voyage périlleux vers l'inconnu.", watchtime: 98 },
          { titre: "Pillage", duree: "45min", minia: "ep3S1Viking.png", synopsis: "Ragnar et ses hommes débarquent sur la côte de Northumbrie et mènent leur premier raid sur le monastère de Lindisfarne.", watchtime: 98 },
          { titre: "L'épreuve", duree: "45min", minia: "ep4S1Viking.png", synopsis: "De retour à Kattegat avec un trésor impressionnant et le moine Athelstan, Ragnar doit affronter la jalousie du Jarl Haraldson.", watchtime: 98 },
          { titre: "Le raid", duree: "45min", minia: "ep5S1Viking.png", synopsis: "Le Jarl Haraldson lance une attaque surprise contre la ferme de Ragnar, contraignant ce dernier et sa famille à fuir.", watchtime: 98 },
          { titre: "Enterrement des morts", duree: "45min", minia: "ep6S1Viking.png", synopsis: "Ragnar défie le Jarl Haraldson dans un combat singulier à mort pour le trône de Kattegat.", watchtime: 98 },
          { titre: "La rançon", duree: "45min", minia: "ep7S1Viking.png", synopsis: "Ragnar et ses guerriers naviguent de nouveau vers l'Angleterre et négocient avec le roi Aelle de Northumbrie.", watchtime: 98 },
          { titre: "Le sacrifice", duree: "45min", minia: "ep8S1Viking.png", synopsis: "Tous les neuf ans, les clans vikings se rassemblent au temple sacré d'Uppsala pour rendre hommage aux dieux.", watchtime: 98 },
          { titre: "Tout change", duree: "45min", minia: "ep9S1Viking.png", synopsis: "Sur ordre du roi Horik, Ragnar se rend en Götaland pour négocier un litige territorial avec le Jarl Borg.", watchtime: 45 }
        ]
      },
      {
        saison: 2,
        episodes: [
          { titre: "Frères ennemis", duree: "45min", minia: "ep1S2Viking.png", synopsis: "Le combat fait rage entre Ragnar et Rollo, allié au Jarl Borg contre son propre frère.", watchtime: 0 },
          { titre: "Fragile alliance", duree: "45min", minia: "ep2S2Viking.png", synopsis: "Quatre ans plus tard, Ragnar prépare une nouvelle expédition vers l'Ouest avec le roi Horik.", watchtime: 0 }
        ]
      }
    ]
  },

  // --- LUPIN ("le pain" phonétique) ---
  {
    titre: "Lupin",
    type: "Serie",
    annee: "2021",
    restriction: "+12",
    resolutionmax: "4K",
    genre: "Policier, Drame, Mystère",
    realisation: "Louis Leterrier, Marcela Said",
    distribution: "Omar Sy, Ludivine Sagnier, Antoine Gouy, Soufiane Guerrab",
    synopsis: `Il y a 25 ans, la vie du jeune Assane Diop est bouleversée lorsque son père meurt après avoir été accusé d'un vol qu'il n'a pas commis. Aujourd'hui, Assane s'inspire de son héros de toujours, Arsène Lupin, pour venger son père et dévoiler la vérité.`,
    favori: true,
    download: true,
    watchtime: 65,
    view: 1200000,
    miniPortrait: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/sgxHA1ylUCE9t7UmhI29fqWdKyj.jpg",
    miniPaysage: "https://image.tmdb.org/t/p/original/9HbMpzS30S5g6vS7n5sY0K2dK6C.jpg",
    titleIMG: "",
    saison: [
      {
        saison: 1,
        episodes: [
          { titre: "Chapitre 1 : Le Collier", duree: "52min", minia: "https://image.tmdb.org/t/p/w500/9HbMpzS30S5g6vS7n5sY0K2dK6C.jpg", synopsis: "Assane conçoit un plan audacieux pour dérober le collier de Marie-Antoinette vendu aux enchères au Louvre.", watchtime: 98 },
          { titre: "Chapitre 2 : L'Illusion", duree: "53min", minia: "https://image.tmdb.org/t/p/w500/sgxHA1ylUCE9t7UmhI29fqWdKyj.jpg", synopsis: "Assane s'infiltre dans une prison sous une fausse identité afin d'interroger un ancien compagnon de cellule de son père.", watchtime: 65 },
          { titre: "Chapitre 3 : Le Commissaire", duree: "48min", minia: "https://image.tmdb.org/t/p/w500/9HbMpzS30S5g6vS7n5sY0K2dK6C.jpg", synopsis: "Assane enlève le commissaire Dumont pour lui soutirer des aveux sur le complot orchestré contre son père.", watchtime: 0 }
        ]
      }
    ]
  },

  // --- LE PARRAIN / PAIN & GAIN (couvrant aussi les variantes de "le pain") ---
  {
    titre: "Le Parrain",
    type: "Film",
    duree: "2h55",
    restriction: "+16",
    resolutionmax: "4K",
    genre: "Drame, Policier",
    annee: "1972",
    realisation: "Francis Ford Coppola",
    distribution: "Marlon Brando, Al Pacino, James Caan, Robert Duvall",
    synopsis: `En 1945, à New York, les Corleone forment l'une des familles mafieuses les plus puissantes. Quand Don Vito Corleone refuse d'entrer dans le trafic de drogue avec les Tattaglia, une guerre des gangs éclate et oblige son fils Michael à embrasser le destin familial.`,
    favori: true,
    download: false,
    watchtime: 85,
    view: 980000,
    miniPortrait: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    miniPaysage: "https://image.tmdb.org/t/p/original/tmU7GeKVybMWF92GlZ16G73J05P.jpg",
    titleIMG: ""
  },
  {
    titre: "No Pain No Gain",
    type: "Film",
    duree: "2h09",
    restriction: "+12",
    resolutionmax: "HD",
    genre: "Action, Comédie, Policier",
    annee: "2013",
    realisation: "Michael Bay",
    distribution: "Mark Wahlberg, Dwayne Johnson, Anthony Mackie, Ed Harris",
    synopsis: `À Miami, Daniel Lugo, coach sportif lassé de sa condition modeste, recrute deux bodybuilders pour kidnapper un riche client et lui extorquer toute sa fortune. Une histoire inspirée de faits réels ahurissants.`,
    favori: false,
    download: false,
    watchtime: 0,
    view: 450000,
    miniPortrait: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/rMhK6b6hT7eMhFwQ0f8kY4zYf6U.jpg",
    miniPaysage: "https://image.tmdb.org/t/p/original/bU5mF7L6Xyv9vXk5qO6ZtXJbL3L.jpg",
    titleIMG: ""
  },

  // --- FILMS AVEC ASSETS LOCAUX DISPONIBLES DANS public/minia/ ---
  {
    titre: "Scarface",
    type: "Film",
    duree: "2h50",
    restriction: "+18",
    resolutionmax: "4K",
    genre: "Policier, Drame",
    annee: "1983",
    realisation: "Brian De Palma",
    distribution: "Al Pacino, Michelle Pfeiffer, Steven Bauer, Robert Loggia",
    synopsis: `En 1980, Tony Montana quitte Cuba lors de l'exode de Mariel pour s'installer à Miami. Son ambition impitoyable et son appétit de pouvoir le propulsent rapidement au sommet du cartel de la drogue.`,
    favori: true,
    download: true,
    watchtime: 75,
    view: 850000,
    miniPortrait: "ScarfacePortrait.jpg",
    miniPaysage: "ScarfacePaysage.jpg",
    titleIMG: "Scarface.png"
  },
  {
    titre: "Star Wars : Épisode III - La Revanche des Sith",
    type: "Film",
    duree: "2h20",
    restriction: "+12",
    resolutionmax: "4K",
    genre: "Science-Fiction, Action, Aventure",
    annee: "2005",
    realisation: "George Lucas",
    distribution: "Hayden Christensen, Ewan McGregor, Natalie Portman, Ian McDiarmid",
    synopsis: `La Guerre des Clones touche à sa fin. Anakin Skywalker, séduit par les promesses de pouvoir du Chancelier Palpatine, bascule peu à peu du Côté Obscur de la Force pour devenir Dark Vador.`,
    favori: true,
    download: true,
    watchtime: 35,
    view: 920000,
    miniPortrait: "Starwars3Portrait.jpg",
    miniPaysage: "Starwars3Paysage.jpg",
    titleIMG: "StarwarsTitle.png"
  },
  {
    titre: "Star Wars : Épisode V - L'Empire contre-attaque",
    type: "Film",
    duree: "2h04",
    restriction: "Tous publics",
    genre: "Science-Fiction, Aventure",
    resolutionmax: "4K",
    annee: "1980",
    realisation: "Irvin Kershner",
    distribution: "Mark Hamill, Harrison Ford, Carrie Fisher, Billy Dee Williams",
    synopsis: `Après la destruction de l'Étoile de la Mort, l'Empire traque les Rebelles à travers la galaxie. Luke Skywalker se rend sur le monde marécageux de Dagobah pour apprendre les voies de la Force auprès de Yoda.`,
    favori: false,
    download: false,
    watchtime: 0,
    view: 890000,
    miniPortrait: "Starwars5Portrait.jpg",
    miniPaysage: "Starwars5Paysage.png",
    titleIMG: "StarwarsTitle.png"
  },
  {
    titre: "Transformers",
    type: "Film",
    duree: "2h24",
    restriction: "+12",
    genre: "Action, Science-Fiction",
    resolutionmax: "HD",
    annee: "2007",
    realisation: "Michael Bay",
    distribution: "Shia LaBeouf, Megan Fox, Josh Duhamel, Tyrese Gibson",
    synopsis: `Une guerre millénaire entre les Autobots et les Decepticons trouve son dénouement sur Terre lorsque l'adolescent Sam Witwicky achète sa première voiture, qui s'avère être le protecteur Bumblebee.`,
    favori: false,
    download: false,
    watchtime: 0,
    view: 670000,
    miniPortrait: "Transformers1Portrait.jpg",
    miniPaysage: "TransformersPaysage.jpg",
    titleIMG: "TransformersTitle.png"
  },
  {
    titre: "Transformers 3 : La Face cachée de la Lune",
    type: "Film",
    duree: "2h34",
    restriction: "+12",
    genre: "Action, Science-Fiction",
    resolutionmax: "4K",
    annee: "2011",
    realisation: "Michael Bay",
    distribution: "Shia LaBeouf, Rosie Huntington-Whiteley, Josh Duhamel, John Malkovich",
    synopsis: `Les Autobots découvrent qu'un vaisseau cybertronien écrasé sur la face cachée de la Lune cachait une technologie capable de sauver leur planète d'origine, éveillant la convoitise des Decepticons.`,
    favori: true,
    download: true,
    watchtime: 50,
    view: 710000,
    miniPortrait: "Transformers3Portrait.jpg",
    miniPaysage: "Transformers3Paysage.jpg",
    titleIMG: "TransformersTitle.png"
  },
  {
    titre: "Avengers",
    type: "Film",
    duree: "2h23",
    restriction: "+12",
    genre: "Action, Science-Fiction, Aventure",
    resolutionmax: "HD",
    annee: "2012",
    realisation: "Joss Whedon",
    distribution: "Robert Downey Jr., Chris Evans, Scarlett Johansson, Mark Ruffalo, Chris Hemsworth",
    synopsis: `Face à la menace imminente d'une invasion extraterrestre menée par Loki, Nick Fury rassemble l'équipe des Avengers pour sauver la planète de l'anéantissement.`,
    favori: true,
    download: true,
    watchtime: 70,
    view: 990000,
    miniPortrait: "AvergersPortrait.jpg",
    miniPaysage: "AvengersPaysage.png",
    titleIMG: "AvergersinfinitywarTitle.png"
  },

  // --- CATALOGUE BDD EXTENDU (Films et Séries avec gestion des données incomplètes) ---
  {
    titre: "Inception",
    type: "Film",
    duree: "2h28",
    annee: "2010",
    genre: "Science-Fiction, Action",
    restriction: "+12",
    resolutionmax: "4K",
    realisation: "Christopher Nolan",
    distribution: "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page, Tom Hardy",
    synopsis: `Dom Cobb est un voleur expérimenté dans l'art périlleux de l'extraction : sa spécialité consiste à s'approprier les précieux secrets d'un individu enfouis au plus profond de son subconscient pendant qu'il rêve.`,
    favori: true,
    download: false,
    watchtime: 40,
    view: 990000,
    affiche: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    miniPortrait: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    miniPaysage: "https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
    titleIMG: ""
  },
  {
    titre: "Breaking Bad",
    type: "Serie",
    annee: "2008-2013",
    genre: "Drame, Policier, Thriller",
    restriction: "+16",
    resolutionmax: "4K",
    realisation: "Vince Gilligan",
    distribution: "Bryan Cranston, Aaron Paul, Anna Gunn, Dean Norris",
    synopsis: `Walter White, professeur de chimie au lycée, découvre qu'il est atteint d'un cancer du poumon incurable. Pour assurer l'avenir financier de sa famille, il s'associe avec l'un de ses anciens élèves pour fabriquer et vendre de la méthamphétamine.`,
    favori: true,
    download: true,
    watchtime: 80,
    view: 1500000,
    affiche: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    miniPortrait: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    miniPaysage: "https://image.tmdb.org/t/p/original/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
    titleIMG: "",
    saisons: 5
  },
  {
    titre: "The Dark Knight",
    type: "Film",
    duree: "2h32",
    annee: "2008",
    genre: "Action, Policier, Drame",
    restriction: "+12",
    resolutionmax: "4K",
    realisation: "Christopher Nolan",
    distribution: "Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine",
    synopsis: `Avec l'aide du lieutenant Jim Gordon et du procureur Harvey Dent, Batman s'efforce de démanteler les organisations criminelles de Gotham. Mais leur plan est mis à rude épreuve par l'apparition du Joker, un génie du crime semant l'anarchie pure.`,
    favori: true,
    download: false,
    watchtime: 60,
    view: 1300000,
    affiche: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    miniPortrait: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    miniPaysage: "https://image.tmdb.org/t/p/original/hkBaDkMWbLaf8B1rWsKX7Ehw3nv.jpg",
    titleIMG: ""
  },
  {
    titre: "Stranger Things",
    type: "Serie",
    annee: "2016-2025",
    genre: "Science-Fiction, Drame, Horreur",
    restriction: "+16",
    resolutionmax: "4K",
    realisation: "The Duffer Brothers",
    distribution: "Millie Bobby Brown, Finn Wolfhard, Winona Ryder, David Harbour",
    synopsis: `À Hawkins, en 1983, un jeune garçon disparaît mystérieusement. Ses amis, sa famille et la police locale cherchent des réponses et se retrouvent confrontés à des expériences gouvernementales secrètes et à une fillette aux étranges pouvoirs.`,
    favori: true,
    download: true,
    watchtime: 55,
    view: 1400000,
    affiche: "https://image.tmdb.org/t/p/w500/x2LSRK2Cm7MZhjluni1msVJ3wDF.jpg",
    miniPortrait: "https://image.tmdb.org/t/p/w500/x2LSRK2Cm7MZhjluni1msVJ3wDF.jpg",
    miniPaysage: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    titleIMG: "",
    saisons: 4
  },
  {
    titre: "Pulp Fiction",
    type: "Film",
    duree: "2h34",
    annee: "1994",
    genre: "Thriller, Policier",
    restriction: "+16",
    resolutionmax: "4K",
    realisation: "Quentin Tarantino",
    distribution: "John Travolta, Samuel L. Jackson, Uma Thurman, Bruce Willis",
    synopsis: `L'odyssée sanglante et burlesque de petits malfrats dans la jungle de Los Angeles à travers trois histoires qui s'entrecroisent : deux tueurs à gages philosophes, la femme d'un parrain et un boxeur en cavale.`,
    favori: false,
    download: false,
    watchtime: 0,
    view: 1100000,
    affiche: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    miniPortrait: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    miniPaysage: "https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    titleIMG: ""
  },
  {
    titre: "Game of Thrones",
    type: "Serie",
    annee: "2011-2019",
    genre: "Drame, Fantasy, Action",
    restriction: "+18",
    resolutionmax: "4K",
    realisation: "David Benioff, D.B. Weiss",
    distribution: "Emilia Clarke, Peter Dinklage, Kit Harington, Lena Headey",
    synopsis: `Sur le continent de Westeros, neuf familles nobles rivalisent pour le contrôle du Trône de Fer, tandis qu'une ancienne menace surnaturelle refait surface au-delà du Mur au Nord.`,
    favori: false,
    download: false,
    watchtime: 0,
    view: 1800000,
    affiche: "https://image.tmdb.org/t/p/w500/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
    miniPortrait: "https://image.tmdb.org/t/p/w500/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
    miniPaysage: "https://image.tmdb.org/t/p/original/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
    titleIMG: "",
    saisons: 8
  },
  {
    titre: "Interstellar",
    type: "Film",
    duree: "2h49",
    annee: "2014",
    genre: "Science-Fiction, Drame",
    restriction: "Tous publics",
    resolutionmax: "4K",
    realisation: "Christopher Nolan",
    distribution: "Matthew McConaughey, Anne Hathaway, Jessica Chastain, Michael Caine",
    synopsis: `Alors que la Terre se meurt, un groupe d'explorateurs franchit une faille spatio-temporelle récemment découverte pour trouver une nouvelle planète capable d'abriter l'humanité.`,
    favori: true,
    download: false,
    watchtime: 88,
    view: 1250000,
    affiche: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    miniPortrait: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    miniPaysage: "https://image.tmdb.org/t/p/original/rAiYTsqJJR9voeh8NtFCj0XJX7d.jpg",
    titleIMG: ""
  },
  {
    titre: "The Office",
    type: "Serie",
    annee: "2005-2013",
    genre: "Comédie",
    restriction: "+12",
    resolutionmax: "HD",
    realisation: "Greg Daniels",
    distribution: "Steve Carell, Rainn Wilson, John Krasinski, Jenna Fischer",
    synopsis: `Le quotidien loufoque et hilarant des employés d'une fabrique de papier à Scranton en Pennsylvanie sous la houlette de leur patron déjanté Michael Scott.`,
    favori: false,
    download: false,
    watchtime: 0,
    view: 950000,
    affiche: "https://image.tmdb.org/t/p/w500/7DJKHzAi83BmQrWLrYYOqcoKfhR.jpg",
    miniPortrait: "https://image.tmdb.org/t/p/w500/7DJKHzAi83BmQrWLrYYOqcoKfhR.jpg",
    miniPaysage: "https://image.tmdb.org/t/p/original/7DJKHzAi83BmQrWLrYYOqcoKfhR.jpg",
    titleIMG: "",
    saisons: 9
  },
  {
    titre: "Parasite",
    type: "Film",
    duree: "2h12",
    annee: "2019",
    genre: "Thriller, Drame, Comédie noire",
    restriction: "+12",
    resolutionmax: "4K",
    realisation: "Bong Joon-ho",
    distribution: "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong, Choi Woo-shik",
    synopsis: `Toute la famille de Ki-taek est au chômage et vit d'expédients dans un demi-sous-sol. Jusqu'au jour où le fils réussit à se faire embaucher comme professeur particulier pour la fille d'une richissime famille.`,
    favori: false,
    download: false,
    watchtime: 0,
    view: 850000,
    affiche: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    miniPortrait: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    miniPaysage: "https://image.tmdb.org/t/p/original/hiKmpISvlEiB8io5Z1WjhOqd1B9.jpg",
    titleIMG: ""
  },
  {
    titre: "The Crown",
    type: "Serie",
    annee: "2016-2023",
    genre: "Drame, Histoire",
    restriction: "+12",
    resolutionmax: "4K",
    realisation: "Peter Morgan",
    distribution: "Claire Foy, Olivia Colman, Imelda Staunton, Matt Smith",
    synopsis: `Cette fresque historique retrace la vie de la Reine Elizabeth II depuis son mariage en 1947 jusqu'aux crises politiques et drames personnels ayant forgé la monarchie britannique moderne.`,
    favori: false,
    download: false,
    watchtime: 0,
    view: 780000,
    affiche: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/snrhOM9JOY3i7UGNDZBfBakiq4n.jpg",
    miniPortrait: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/snrhOM9JOY3i7UGNDZBfBakiq4n.jpg",
    miniPaysage: "https://image.tmdb.org/t/p/original/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
    titleIMG: "",
    saisons: 6
  },
  {
    titre: "Ginny & Georgia",
    type: "Serie",
    annee: "2021",
    genre: "Drame, Comédie",
    restriction: "+16",
    resolutionmax: "HD",
    realisation: "Sarah Lampert",
    distribution: "Brianne Howey, Antonia Gentry, Diesel La Torraca",
    synopsis: `Ginny Miller, une jeune fille de 15 ans plus mature que sa propre mère Georgia, tente de trouver ses repères dans une petite ville de Nouvelle-Angleterre après des années de vie nomade.`,
    favori: false,
    download: false,
    watchtime: 0,
    view: 540000,
    affiche: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/vOwunzW4dx3n0J5mH40n9jTRSwY.jpg",
    miniPortrait: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/vOwunzW4dx3n0J5mH40n9jTRSwY.jpg",
    miniPaysage: "",
    titleIMG: "",
    saisons: 2
  },
  {
    titre: "À bout",
    type: "Film",
    duree: "1h24",
    annee: "2010",
    genre: "Action, Thriller, Policier",
    restriction: "+12",
    resolutionmax: "HD",
    realisation: "Fred Cavayé",
    distribution: "Gilles Lellouche, Roschdy Zem, Gérard Lanvin, Elena Anaya",
    synopsis: `Samuel, infirmier bienveillant, voit sa vie basculer lorsque sa femme enceinte est kidnappée sous ses yeux. Pour la sauver, il doit aider un criminel blessé à s'évader de l'hôpital.`,
    favori: false,
    download: false,
    watchtime: 0,
    view: 320000,
    affiche: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/v5Xsg4NGS4mJ3DpwuN5kUnZxhL3.jpg",
    miniPortrait: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/v5Xsg4NGS4mJ3DpwuN5kUnZxhL3.jpg",
    miniPaysage: "",
    titleIMG: ""
  },
  {
    titre: "K.O.",
    type: "Film",
    duree: "45min",
    annee: "2023",
    genre: "Drame, Sport",
    restriction: "+16",
    resolutionmax: "HD",
    realisation: "Fabrice Éboué",
    distribution: "Cyril Gane, Alice Belaïdi, Nassim Lyes",
    synopsis: `Un ancien combattant d'arts martiaux mixtes affronte une violente organisation criminelle marseillaise pour retrouver le fils d'un adversaire tué par accident dans l'octogone.`,
    favori: false,
    download: false,
    watchtime: 0,
    view: 290000,
    affiche: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/uTbQg4zQ0eGXlKl8imLu64LLJQX.jpg",
    miniPortrait: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/uTbQg4zQ0eGXlKl8imLu64LLJQX.jpg",
    miniPaysage: "",
    titleIMG: ""
  },
  {
    titre: "You",
    type: "Serie",
    annee: "2018-2024",
    genre: "Thriller, Drame, Crime",
    restriction: "+16",
    resolutionmax: "4K",
    realisation: "Greg Berlanti, Sera Gamble",
    distribution: "Penn Badgley, Victoria Pedretti, Elizabeth Lail",
    synopsis: `Joe Goldberg, gérant discret d'une librairie new-yorkaise, développe des obsessions toxiques et maladives envers les femmes qu'il convoite, se servant d'Internet et des réseaux sociaux pour les espionner.`,
    favori: false,
    download: false,
    watchtime: 0,
    view: 890000,
    affiche: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/doavJnd27DZv6wxruPUC38Od9NC.jpg",
    miniPortrait: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/doavJnd27DZv6wxruPUC38Od9NC.jpg",
    miniPaysage: "",
    titleIMG: "",
    saisons: 4
  },
  {
    titre: "Black Widow",
    type: "Film",
    duree: "2h14",
    annee: "2021",
    genre: "Action, Aventure, Science-Fiction",
    restriction: "+12",
    resolutionmax: "4K",
    realisation: "Cate Shortland",
    distribution: "Scarlett Johansson, Florence Pugh, David Harbour, Rachel Weisz",
    synopsis: `Natasha Romanoff renoue avec les aspects les plus sombres de son passé lorsqu'une dangereuse conspiration liée à son entraînement de veuve noire resurgit. Poursuivie par une force implacable, elle doit renouer avec sa famille désunie.`,
    favori: false,
    download: false,
    watchtime: 0,
    view: 720000,
    affiche: "https://image.tmdb.org/t/p/w500/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg",
    miniPortrait: "https://image.tmdb.org/t/p/w500/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg",
    miniPaysage: "https://image.tmdb.org/t/p/original/keIxh0wPr2Ymj0Btjh4gW7JJ89e.jpg",
    titleIMG: ""
  }
];

export default films;
